# Generated by Django 3.2.4 on 2021-06-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mdt',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='mtext',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='user_info',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
