# Generated by Django 3.2.4 on 2021-06-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20210629_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='update_time',
        ),
    ]
