# Generated by Django 3.2.4 on 2021-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_user_info_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='update_time',
        ),
        migrations.AddField(
            model_name='user_info',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
