# Generated by Django 3.2.4 on 2021-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_user_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
