# Generated by Django 3.2.4 on 2021-06-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_alter_user_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='tod_project',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user_info',
            name='yes_project',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
