# Generated by Django 3.2.4 on 2021-06-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_user_info_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='yesterday',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
