# Generated by Django 3.2.4 on 2021-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_user_info_yesterday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='yesterday',
        ),
        migrations.AddField(
            model_name='user_info',
            name='yesterday_temp',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
