# Generated by Django 3.2.4 on 2021-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_auto_20210630_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='today_temp',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
