# Generated by Django 3.2.4 on 2021-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_user_info_today_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='update_project',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
