# Generated by Django 3.2.4 on 2021-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_user_info_update_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='day1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
